server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file:///Users/juhyeong/Desktop/DevOps-Playground/msa_with_spring_cloud/configuration_repo
